name: Build

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: windows-latest
            arch: x64
          # - os: macos-latest
          #   arch: arm64
          # - os: ubuntu-latest
          #   arch: x64
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm

      - run: npm ci

      - run: npm run dist

      - uses: actions/upload-artifact@v4
        with:
          name: llama-cpp-desktop-${{ matrix.config.arch }}
          path: dist/

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist/

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
